service: serverless-example

frameworkVersion: "3"

plugins:
  - serverless-plugin-typescript
  - serverless-plugin-optimize
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3000
    stageVariables:
      foo: "bar"
    # noPrependStageInUrl: true
    # https://github.com/dougmoscrop/serverless-http/issues/86
    # https://github.com/dougmoscrop/serverless-http/issues/86#issuecomment-627514571
    # https://github.com/dherault/serverless-offline/issues/911
    # https://github.com/dherault/serverless-offline/issues/88
    # curl http://localhost:3000/dev/hello が curl http://localhost:3000/hello になる

  serverlessPluginTypescript:
    # tsConfigFileLocation: './tsconfig.lambda.json'
    tsConfigFileLocation: './tsconfig.build.json'
    #tsConfigFileLocation: './tsconfig.json'
  defaultStage: dev
  environment:
    dev: ${file(./env/site-dev.yml)}
    prod: ${file(./env/site-prod.yml)}

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: ${opt:stage, self:custom.defaultStage}

package:
  individually: true
  patterns:
    - '!src/**'
    - '!test/**'
    # - 'node_modules/**'
    - dist/**
    - node_modules
    - '!node_modules/.bin'
    - '!node_modules/.bin/*'

  # Support for "package.include" and "package.exclude" will be removed in the next major release. Please use "package.patterns" instead
  # include:
  #   #- src/** 
  #   - dist/**
  #   - node_modules
  # exclude:
  #   # - '**'
  #   # - src/**   pattersで先頭!で除外
  #   # - test/**  pattersで先頭!で除外
  #   - 'node_modules/.bin'
  #   - 'node_modules/.bin/*'
  excludeDevDependencies: true

functions:
  main:
    handler: dist/main.handler
    events:
      - http:
          path: '/'
          method: ANY
          cors: true
      - http:
          method: ANY
          path: '{proxy+}'
          cors: true
